# Generated by Django 4.0.1 on 2022-02-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='name_img',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
