# Generated by Django 4.0.1 on 2022-02-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0002_alter_imagemodel_name_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imageModel',
            new_name='loadImageModel',
        ),
    ]
