# Generated by Django 4.0.1 on 2022-02-06 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0003_rename_imagemodel_loadimagemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loadImageModel',
            new_name='imageModel',
        ),
    ]
